// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef scntrn_gui_official_h
#define scntrn_gui_official_h
#include <stdio.h>
#include <string.h>
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Light_Button.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_File_Browser.H>
#include <FL/Fl_File_Chooser.H>
#include <FL/Fl_File_Icon.H>
//#include <FL/Fl_Browser.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Text_Display.H>

class scntrngui {
public:
  Fl_Double_Window* make_window();
  static Fl_Menu_Item menu_[];
};
void create_exam(Fl_Widget* w, void* v);
void extra_callback(Fl_Choice *w, void*);
void fc_callback(Fl_File_Chooser *fc, void *data);
void show_callback();
#endif
