// generated by Fast Light User Interface Designer (fluid) version 1.0305

#include <iostream>

#ifndef AngieAttempt_h
#define AngieAttempt_h
#include <FL/Fl.H>
void callback_button(Fl_Widget* widg, void* userdata);
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window* win_app;
#include <FL/Fl_Input.H>
extern Fl_Input* inp_box;
#include <FL/Fl_Output.H>
extern Fl_Output* out_box;
#include <FL/Fl_Button.H>
#include <FL/Fl_Choice.H>
Fl_Double_Window* make_window();
extern Fl_Menu_Item menu_[];
#endif
#include <FL\Fl_Menu_Bar.H>




void callback_button(Fl_Widget* widg, void* userdata) {
    std::cout << "button click\n";
    char const* text = inp_box->value();
    out_box->value(text);
}


Fl_Double_Window* make_choice_window() {
    printf("Hello, World!\n");
    { win_app = new Fl_Double_Window(885, 280);
    { Fl_Choice* o1 = new Fl_Choice(245, 55, 320, 45, "?\?\?");
    o1->down_box(FL_BORDER_BOX);
    o1->menu(menu_);
    } // Fl_Choice* o
    { new Fl_Button(370, 195, 135, 25, "Yeet");
    } // Fl_Button* o
    win_app->end();
    }
    return win_app;
}

Fl_Double_Window* make_new_course_window() {
    win_app = new Fl_Double_Window(480, 240,"New Course");
    //TODO
    return win_app;
}
Fl_Double_Window* make_new_exam_window() {
    win_app = new Fl_Double_Window(480, 240, "New Exam");
    //TODO
    return win_app;
}
Fl_Double_Window* make_new_questions_window() {
    win_app = new Fl_Double_Window(480, 240, "New Question");
    //TODO
    return win_app;
}
Fl_Double_Window* make_open_course_window() {
    win_app = new Fl_Double_Window(480, 240, "Open Course");
    //TODO
    return win_app;
}
Fl_Double_Window* make_open_exam_window() {
    win_app = new Fl_Double_Window(480, 240, "Open Exam");
    //TODO
    return win_app;
}
Fl_Double_Window* make_open_questions_window() {
    win_app = new Fl_Double_Window(480, 240, "Open Questions");
    //TODO
    return win_app;
}


void callback_button_create(Fl_Widget* widg, void* userdata) {
    Fl_Window* win = make_choice_window();
    win->show();
}
void callback_new_course(Fl_Widget* widg, void* userdata) {
    Fl_Window* win = make_new_course_window();
    win->show();
}
void callback_open_course(Fl_Widget* widg, void* userdata) {
    Fl_Window* win = make_open_course_window();
    win->show();
}
void callback_new_exam(Fl_Widget* widg, void* userdata) {
    Fl_Window* win = make_new_exam_window();
    win->show();
}
void callback_open_exam(Fl_Widget* widg, void* userdata) {
    Fl_Window* win = make_open_exam_window();
    win->show();
}

void callback_new_questions(Fl_Widget* widg, void* userdata) {
    Fl_Window* win = make_new_questions_window();
    win->show();
}
void callback_open_questions(Fl_Widget* widg, void* userdata) {
    Fl_Window* win = make_open_questions_window();
    win->show();
}



Fl_Double_Window* win_app = (Fl_Double_Window*)0;

Fl_Input* inp_box = (Fl_Input*)0;

Fl_Output* out_box = (Fl_Output*)0;

Fl_Menu_Item Mainmenu_[] = {
 {"&Courses", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
  {"&New", 0x4006e,  (Fl_Callback*)callback_new_course, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"&Open", 0x4006f,   (Fl_Callback*)callback_open_course, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"&Exams", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"&New", 0x4006e,   (Fl_Callback*)callback_new_exam, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"&Open", 0x4006f,   (Fl_Callback*)callback_open_exam, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"&Questions", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"&New", 0x4006e,   (Fl_Callback*)callback_new_questions, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"&Open", 0x4006f,   (Fl_Callback*)callback_open_questions, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item menu_[] = {
 {"Opt1", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Opt2", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Double_Window* make_window() {
    printf("Hello, World!\n");
    { win_app = new Fl_Double_Window(640, 480);
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 640, 20);
    o->menu(Mainmenu_);
    }
    
    /*
    { inp_box = new Fl_Input(295, 191, 205, 24, "input:");
    inp_box->when(FL_WHEN_CHANGED);
    } // Fl_Input* inp_box
    { out_box = new Fl_Output(235, 151, 205, 24, "output:");
    } // Fl_Output* out_box
    { Fl_Button* o = new Fl_Button(25, 25, 64, 20, "button");
    o->callback((Fl_Callback*)callback_button);
    } // Fl_Button* o
    { Fl_Button* o2 = new Fl_Button(200, 25, 64, 20, "button2");
    o2->callback((Fl_Callback*)callback_button_create);
    } // Fl_Button* o
    */
    win_app->end();
    } // Fl_Double_Window* win_app
    return win_app;
}




int main(int argc, char** argv) {
    Fl_Window* win = make_window();
    win->show();
    return Fl::run();
}


